=== void-zenith/GeetMandu-XML/catalog_19031843.dtd
<!ELEMENT store (storedetails,songs,footer)>

<!ELEMENT storedetails (logo,info,slogan)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT info (storename,address,phones,website)>
<!ELEMENT storename (#PCDATA)>
<!ELEMENT address (street,city,state)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT phones (phone+)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT slogan (#PCDATA)>

<!ATTLIST store name CDATA #REQUIRED
        xmlns:xsi CDATA #FIXED "http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ATTLIST phone type (primary|secondary) #IMPLIED>

<!ELEMENT songs (song+)>
<!ELEMENT song (image,songinfo,buy)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT songinfo (name,releaseDate,recorded?,studios?,length,labels?,directors?,producers,
writers,singers,genres,publishers?,distributors?,achievements?)>
<!ELEMENT buy (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT releaseDate (#PCDATA)>
<!ELEMENT recorded (#PCDATA)>
<!ELEMENT studios (studio+)>
<!ELEMENT studio (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT labels (label+)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT directors (director+)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT producers (producer+)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT writers (writer+)>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT singers (singer+)>
<!ELEMENT singer (#PCDATA)>
<!ELEMENT genres (genre+)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT publishers (publisher+)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT distributors (distributor+)>
<!ELEMENT distributor (#PCDATA)>
<!ELEMENT achievements (achievement+)>
<!ELEMENT achievement (#PCDATA)>

<!ATTLIST song s_id ID #REQUIRED
        genre (Jazz|Rock|Rap|Pop|Dubstep) #IMPLIED
        price CDATA #REQUIRED>
<!ATTLIST image img_id ID #REQUIRED>
<!ATTLIST buy buy_id IDREF #REQUIRED>
<!ATTLIST singer siType (Lead-Singer|Backup-Singer) #IMPLIED>

<!ELEMENT footer (socials,privacy)>
<!ELEMENT socials (social*)>
<!ELEMENT social (#PCDATA)>
<!ELEMENT privacy (#PCDATA)>
<!ATTLIST social social CDATA #REQUIRED>

=== void-zenith/GeetMandu-XML/catalog_19031843.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--linkning stylesheet with xml-->
<?xml-stylesheet type="text/css" href="catalog_19031843.css"?> 
<!--linking dtd with xml-->
<!DOCTYPE store SYSTEM "catalog_19031843.dtd">
<!--starting xml document-->
<store name="GeetMandu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
			xsi:noNamespaceSchemaLocation="catalog_19031843.xsd">  <!--store the parent element-->
    <storedetails>  <!--storedetails child of store i.e. parent element-->
        <logo></logo>   <!--to insert logo-->
        <info>          <!--for info of the store-->
            <storename>GeetMandu</storename>  <!--name of the store-->
            <address>                          <!--address of the store-->
                <street>Lazimpat,</street>      
                <city>Kathmandu,</city>
                <state>Bagmati Province</state>
            </address>
            <phones>        <!--phone of the store-->
                <phone type="primary">01-420691, </phone>
                <phone type="secondary">9841761333 </phone>
            </phones>    
            <website>www.GeetMandu.com.np</website> <!--website of the store-->
        </info>
        <slogan>You are What you Listen To!</slogan>  <!--slogan of the store-->
    </storedetails>     <!--ending of storedetails -->

    <songs>     <!--songs child of store i.e. parent element-->
        <song s_id="s01" genre="Pop" price="$39.99"> <!--each song data is entered inside of it-->
            <image img_id="img01">          <!--image of a child-->
            </image>
            <songinfo>              <!--details of the song-->
                <name>Name: SOMEONE YOU LOVED</name>    <!--name of the song-->
                <releaseDate>Released Date: 8 November 2018</releaseDate>       <!--releaseDate of the song-->
                <length>Length: 3:53</length>           <!--length of the song-->
                <producers>     <!--details of producers of the song is entered inside-->
                    <producer>Producer(s): TMS</producer>   <!--producer of the song-->
                </producers>
                <writers>           <!--details of writers of the song is entered inside-->
                    <writer>Writer(s): LEWIS CAPALDI,</writer>  <!--writer of the song-->
                    <writer>Samuel Romans,</writer>
                    <writer>Thomas Barnes,</writer>
                </writers>
                <singers>       <!--details of singers of the song is entered inside-->
                    <singer siType="Lead-Singer">Singer(s): LEWIS CAPALDI </singer>         <!--singer of the song-->
                </singers>  
                <genres>        <!--genres of song-->
                    <genre>Genre(s): Pop </genre>   <!--each genre-->
                </genres>
                <publishers>        <!--details of publishers of song-->
                    <publisher>Publisher(s): BMG</publisher>    <!--publisher of the song--> 
                    <publisher>Sony Music Entertainment</publisher>
                </publishers>
                <achievements>      <!--details of achievements of song-->
                    <achievement>üèÜBest selling single of 2019</achievement> <!--achievement of the song-->
                    <achievement>üèÜSong of the year 2020 Brit Awards.</achievement>
                </achievements>
            </songinfo> <!--ending of details of the song-->
            <buy buy_id="s01">$39.99</buy>  <!--price of the song-->
        </song><!--ending of song-->
        <song s_id="s02" genre="Rap" price="$29.99"><!--each song data is entered inside of it--> 
            <image img_id="img02">  <!--image of a child-->
            </image>
            <songinfo> <!--details of the song-->
                <name>Name: OLD TOWN ROAD</name> <!--name of the song-->
                <releaseDate>Released Date: 2 December 2018</releaseDate> <!--releaseDate of the song-->
                <studios>   <!--details of the studios of the song-->
                    <studio>Studio(s): CinCoYo (Atlanta, Georgia)</studio> <!--studio of the song-->
                </studios>
                <length>Length: 1:53</length> <!--length of the song-->
                <labels>    <!--details of the labels of the song-->
                    <label>Label(s): Columbia</label> <!--label of the song-->
                </labels>
                <producers> <!--details of producers of the song is entered inside-->
                    <producer>Producer(s): YoungKio</producer>  <!--producer of the song-->
                    <producer> Trent Reznor</producer>  <!--producer of the song-->
                </producers>
                <writers> <!--details of writers of the song is entered inside-->
                    <writer>Writer(s): LEWIS CAPALDI,</writer> <!--writer of the song-->
                    <writer>Montero Hill (Lis Nas X),</writer>  <!--writer of the song-->
                </writers>
                <singers> <!--details of singers of the song is entered inside-->
                    <singer siType="Lead-Singer">Singer(s): Montero Hill (Lis Nas X)</singer> <!--singer of the song-->
                </singers>
                <genres> <!--genres of song-->
                    <genre>Genre(s): Hip Pop,</genre>  <!--each genre-->
                    <genre>Country Rap</genre>  <!--each genre-->
                </genres>
                <distributors>  <!--details of distributors-->
                    <distributor>Distributor(s): Sony Music Entertainment</distributor> <!--distributor-->
                </distributors>
                <achievements> <!--details of achievements of song-->
                    <achievement>üèÜDiamond certification by RIAA in 2019</achievement>  <!--achievement of the song-->
                    <achievement>üèÜTop Rap Song by Billboard Music Awards in 2020</achievement>  <!--achievement of the song-->
                </achievements> 
            </songinfo> <!--ending of details of the song-->
            <buy buy_id="s02">$29.99</buy> <!--price of the song-->
        </song> <!--ending of song-->
        <song s_id="s03" genre="Pop" price="$49.99"> <!--each song data is entered inside of it--> 
            <image img_id="img03">  <!--image of a child-->
            </image>
            <songinfo> <!--details of the song-->
                <name>Name: I DON'T CARE</name> <!--name of the song-->
                <releaseDate>Released Date: 10 May 2019</releaseDate> <!--releaseDate of the song-->
                <length>Length: 3:39</length>  <!--length of the song-->
                <labels>   <!--details of the labels of the song-->
                    <label>Label(s): Atlantic UK</label>   <!--label of the song-->
                    <label> Def Jam</label>  <!--label of the song-->
                    <label>  Warner UK</label>  <!--label of the song-->
                </labels>
                <producers>  <!--details of producers of the song is entered inside-->
                    <producer>Producer(s):FRED</producer>      <!--producer of the song-->
                    <producer> Max Martin</producer>  <!--producer of the song-->
                    <producer> Shellback</producer> <!--producer of the song-->
                </producers>
                <writers>  <!--details of writers of the song is entered inside-->
                    <writer>Writer(s): Ed Sheeren,</writer> <!--writer of the song-->
                    <writer>Fred Gibson,</writer> <!--writer of the song-->
                </writers>
                <singers> <!--details of singers of the song is entered inside-->
                    <singer siType="Lead-Singer">Singer(s): ED SHEERAN,</singer> <!--singer of the song-->
                    <singer siType="Backup-Singer">JUSTIN BIEBER</singer>  <!--singer of the song-->
                </singers>
                <genres>  <!--genres of song-->
                    <genre>Genre(s): Electropop</genre>  <!--each genre-->
                </genres>
                <publishers>  <!--details of publishers of song-->
                    <publisher>Publisher(s): Sony/ATV Harmony</publisher> <!--publisher of the song--> 
                    <publisher>PolyGram</publisher><!--publisher of the song--> 
                </publishers>
            </songinfo> <!--ending of details of the song-->
            <buy buy_id="s03">$49.99</buy><!--price of the song-->
        </song> <!-- ending details of the third song-->
        <song s_id="s04" genre="Pop" price="$59.99"> <!-- details of the fourth song-->
            <image img_id="img04"> 
            </image>    
            <songinfo>
                <name>Name: BAD GUY</name>
                <releaseDate>Released Date: 29 May 2019</releaseDate>
                <length>Length: 3:14</length>
                <labels>
                    <label>Label(s): Darkroom,</label>
                    <label>Interscope</label>
                </labels>
                <directors>
	                <director>Dave Meyers</director>
                </directors>
                <producers>
                    <producer>Producer(s): Finneas O'Connell</producer>
                </producers>
                <writers>
                    <writer>Writer(s): BILLIE EILISH,</writer>
                    <writer>Finneas O'Connell</writer>
                </writers>
                <singers>
                    <singer siType="Lead-Singer">Singer(s): BILLIE EILISH </singer>
                </singers>
                <genres>
                    <genre>Genre(s):Electropop,</genre>
                    <genre>Dance-pop</genre>
                </genres>
                <publishers>
                    <publisher>Publisher(s): Kobalt Music</publisher>
